-*- org-mode -*-

This is a checklist of things to audit when upgrading a Drupal module
from 6.x to 7.x, for the phpbb2drupal module.

Copied from http://drupal.org/update/modules/6/7 on 30/6/2011

* UNSTABLE-1 (2008-Sep-30)

   1. [X] Drupal 7 requires PHP 5.2 or higher
   2. [X] Permissions have titles (required) and descriptions (optional)
   3. [X] Permissions are no longer sorted alphabetically
   4. [X] _comment_load() is now comment_load()
   5. [X] Module .info files must now specify all loadable code files explicitly
   6. [X] The hook_menu() and hook_theme() "file" and "file path" keys have been removed
   7. [X] New permission tables
   8. [X] Use '#markup' not '#value' for markup
   9. [X] Comment status values in the database have flipped so they match node status
  10. [ ] Rebuild functions have changed names
  11. [ ] Use defined constant REQUEST_TIME instead of time()
  12. [ ] referer_uri() has been removed
  13. [ ] Some #process functions have been renamed
  14. [ ] A completely new database API has been added
  15. [ ] file_validate_extensions() enforces check for uid=1
  16. [ ] file_scan_directory() and drupal_system_listing() use preg regular expressions
  17. [ ] Easier check for node form during hook_form_alter()
  18. [ ] Update functions in .install files must include a Doxygen style comment
  19. [ ] Replace drupal_clone() with clone
  20. [ ] Session functions are renamed.

* UNSTABLE-2 (2008-Oct-11)

   1. [ ] Permissions have titles (required) and descriptions (optional)
   2. [ ] hook_nodeapi, hook_node_type, hook_user, and hook_block removed and replaced with families of related functions
   3. [ ] In hook_node_info() change 'module' back to 'base' and change 'node' to 'node_content'
   4. [ ] Use absolute path (constructed from DRUPAL_ROOT) when including a file
   5. [ ] File API reworked, stream notation required, file_unmanaged_* functions
   6. [ ] "administer nodes" permission split into "administer nodes", "access content overview", and "bypass node access"
   7. [ ] New hooks: hook_modules_installed, hook_modules_enabled, hook_modules_disabled, and hook_modules_uninstalled
   8. [ ] drupal_uninstall_module() is now drupal_uninstall_modules()

* UNSTABLE-3 (2008-Nov-11)

   1. [ ] drupal_set_title() uses check_plain() by default
   2. [ ] Changed parameters for drupal_add_js() and drupal_add_css()
   3. [ ] Changed Drupal.behaviors to objects having the methods 'attach' and 'detach'
   4. [ ] Taxonomy CRUD functions renamed and refactored
   5. [ ] New taxonomy hooks for term and vocabulary
   6. [ ] Removed file_set_status()
   7. [ ] Replace 'core', 'module' and 'theme' with 'file' in drupal_add_js()
   8. [ ] Parameters to check_markup() have changed, default format change

* UNSTABLE-4 (2009-Jan-8)

   1. [ ] Schema descriptions are no longer translated
   2. [ ] file_scan_directory() now uses a preg regular expression for the nomask parameter
   3. [ ] Use module_implements not module_list when calling hook implementations
   4. [ ] New hook_js_alter to alter JavaScript
   5. [ ] Changed log out path from 'logout' to 'user/logout' for consistency Note: Link goes to separate sub-page!
   6. [ ] node_load() and node_load_multiple()
   7. [ ] taxonomy_term_load() and taxonomy_term_load_multiple()
   8. [ ] file_load_multiple()
   9. [ ] Taxonomy CRUD functions renamed and refactored
  10. [ ] New taxonomy hooks for term and vocabulary
  11. [ ] Code documentation added to module.api.php
  12. [ ] taxonomy_get_tree()
  13. [ ] Move node, taxonomy, and comment links into $node->content; Deprecate hook_link()
  14. [ ] hook_nodeapi, hook_node_type, hook_user, and hook_block removed and replaced with families of related functions
  15. [ ] Parameters for actions_synchronize() have changed
  16. [ ] Parameters for drupal_http_request() have changed
  17. [ ] db_rewrite_sql() replaced with hook_query_alter()
  18. [ ] Removed FILE_STATUS_TEMPORARY
  19. [ ] New user_cancel API
  20. [ ] Taxonomy db table names have changed to begin with 'taxonomy_'

* UNSTABLE-5 (2009-Jan-26)

   1. [ ] User pictures are now managed files
   2. [ ] drupal_set_session() replaces $_SESSION [NOT ANYMORE]
   3. [ ] Ability to reset JavaScript and CSS
   4. [ ] Moved statistics settings from admin/reports/settings to admin/settings/statistics admin/config/system/statistics and added a new 'administer statistics' permission
   5. [ ] Default parameter when getting variables
   6. [ ] Menu "page callbacks" and blocks should return an array and hook_page_alter() (Render arrays discussion)
   7. [ ] Block module now optional
   8. [ ] Element #type property no longer treated as a theme function in drupal_render()
   9. [ ] Use drupal_render_children() to render an element's children
  10. [ ] Replace node_view() with node_build()

* UNSTABLE-6 (2009-Mar-14)

   1. [ ] JavaScript should be compatible with other libraries than jQuery
   2. [ ] file_scan_directory()'s optional parameters are now an array
   3. [ ] External JavaScript can now be referenced through drupal_add_js()
   4. [ ] user_load_multiple() and hook_user_load(), user_load() signature change, and $reset parameter
   5. [ ] jQuery 1.3.x
   6. [ ] Settings passed locally to JavaScript Behaviors
   7. [ ] file_scan_directory() now uses same property names as file_load()

* UNSTABLE-7 (2009-May-21)

   1. [ ] Moved filter module administrative URLs from admin/settings/filters/* to admin/settings/filter/*
   2. [ ] Added taxonomy_vocabulary_load_multiple()
   3. [ ] Added a new top-level 'international' admin menu item
   4. [ ] Changed hook_menu_link_alter() (removed the $menu parameter)
   5. [ ] Standardized API for static variables and resetting them
   6. [ ] The function drupal_set_html_head() has been renamed to drupal_add_html_head()
   7. [ ] Inline cascading stylesheets from drupal_add_css()
   8. [ ] Attached JavaScript and CSS for forms
   9. [ ] Make sticky tableheaders optional
  10. [ ] Save new users and nodes with specified IDs
  11. [ ] Parameters swapped in book_toc()
  12. [ ] drupal_execute() renamed to drupal_form_submit()
  13. [ ] node_invoke_nodeapi() removed
  14. [ ] Removed $op "rss item" from hook_nodeapi() in favor of 'rss' view mode
  15. [ ] drupal_eval() renamed to php_eval
  16. [ ] "use PHP for settings" permission should be used for all PHP settings rights (replaces "use PHP for block visibility")
  17. [ ] Changes to HTTP header functions
  18. [ ] drupal_get_form() returns a render array instead of a string
  19. [ ] Add Doxygen @file tag to all install files
  20. [ ] Add node_delete_multiple()
  21. [ ] Renamed drupal_set_content() and drupal_get_content()
  22. [ ] Instead of theme('page', ...), think of drupal_set_page_content()
  23. [ ] theme('box') no longer exists
  24. [ ] Node Body and Teaser Changes

* UNSTABLE-8 (2009-Jul-21)

   1. [ ] Node access hooks now have drupal_alter() functions
   2. [ ] Hide empty menu categories with access callback
   3. [ ] Commenting style - use 'Implements hook_foo().' when documenting hooks
   4. [ ] node_get_types($op) replaced by node_type_get_$op()
   5. [ ] Added hook_block_info_alter()
   6. [ ] Renamed module_rebuild_cache() to system_rebuild_module_data(), renamed system_theme_data() to system_rebuild_theme_data(), and added system_get_info()
   7. [ ] Added string context support to t() and format_plural(), changed parameters
   8. [ ] Alternative cache implementations changed
   9. [ ] $teaser parameter changed to $view_mode in node viewing functions and hooks, $node->build_mode property removed
  10. [ ] comment_save() now supports programmatic saving
  11. [ ] comment_validate() has been removed
  12. [ ] Login validation change for distributed authentication modules
  13. [ ] Some login validation functions were removed or changed
  14. [ ] jQuery UI (1.7) was added into core
  15. [ ] comment_node_url() has been removed
  16. [ ] #theme recommended for specifying theme function
  17. [ ] hook_perm() renamed to hook_permission()
  18. [ ] Ability to add multiple JavaScript/CSS files at once
  19. [ ] Removed taxonomy module support for multiple tids and depth in term paths
  20. [ ] file_prepare_directory() (replacement for file_check_directory() will now recursively create directories
  21. [ ] Added comment_load_multiple() and hook_comment_load()
  22. [ ] hook_node_access_records() now applies to unpublished nodes; 'view own unpublished content' permission added
  23. [ ] New tar archive library added
  24. [ ] hook_elements() renamed to hook_element_info()
  25. [ ] Blog API module removed from Drupal core
  26. [ ] drupal_urlencode() replaced by drupal_encode_path()
  27. [ ] Two page caching functions renamed
  28. [ ] MIME types list changed from variable to alter hook/function

* UNSTABLE-9 (2009-Sep-9)

   1. [ ] hook_footer() was removed, $closure became $page_bottom, $page_top added
   2. [ ] Schema descriptions are now plain text instead of HTML
   3. [ ] Related terms functionality was removed from taxonomy.module
   4. [ ] db_result() has been removed; use ->fetchField() instead
   5. [ ] Do not use SELECT COUNT(*) to check for existence of rows in a table
   6. [ ] Added drupal_set_time_limit()
   7. [ ] Module .info files can now optionally specify the version number of the module it depends on
   8. [ ] hook_nodeapi_xxx() becomes hook_node_xxx()
   9. [ ] .module file available during install
  10. [ ] Parameters to function user_authenticate() changed
  11. [ ] JavaScript variable Drupal.jsEnabled has been removed
  12. [ ] xmlrpc() wrapper function removed
  13. [ ] Foreign keys added to core database table schema
  14. [ ] Removed several unnecessary arguments to various hook_user_$op hooks and removed hook_profile_alter
  15. [ ] Many paths to admin screens have changed
  16. [ ] hook_nodeapi, hook_node_type, hook_user, and hook_block removed and replaced with families of related functions
  17. [ ] drupal_add_css() now supports external CSS files
  18. [ ] New hook_comment_presave() for comments
  19. [ ] Weighting of stylesheets
  20. [ ] AHAH/AJAX Processing has changed; #ajax, new 'callback' member of the array, and the callback must be rewritten
  21. [ ] hook_access() removed in favor of hook_node_access()
  22. [ ] hook_filter() and hook_filter_tips() replaced by hook_filter_info()
  23. [ ] Convert class attributes to array in favor of a string
  24. [ ] Schema API now supports date and time types natively
  25. [ ] Added API functions for creating, loading, updating, and deleting user roles and permissions
  26. [ ] New hook: hook_file_url_alter()
  27. [ ] jQuery Once method for applying JavaScript behaviors once
  28. [ ] Database schema (un)installed automatically
  29. [ ] User 1 is now called site maintenance account
  30. [ ] CRUD hooks for menu links: hook_menu_link_insert(), hook_menu_link_update(), hook_menu_link_delete()
  31. [ ] Default text formats have been revamped
  32. [ ] Text formats access is now controlled by permissions, and filter_access() parameters have changed
  33. [ ] The parameters to filter_formats() have changed
  34. [ ] Rename drupal_to_js() and drupal_json() to drupal_json_encode() and drupal_json_output()
  35. [ ] theme_links() has a new parameter 'heading' for accessibility
  36. [ ] API for modules providing search has changed
  37. [ ] All taxonomy functions relating to nodes have been removed or refactored
  38. [ ] Added hook_entity_load()
  39. [ ] All e-mails are considered to originate as HTML
  40. [ ] file_check_directory() renamed to file_prepare_directory()
  41. [ ] Block Cache constants renamed to DRUPAL_CACHE
  42. [ ] File API: $file->filepath renamed to $file->uri
  43. [ ] HTML rendering of form elements has different CSS classes
  44. [ ] Form element value callbacks now always have $form_state argument
  45. [ ] Changes to how Drupal sends email

* UNSTABLE-10 (2009-Nov-2)

   1. [ ] Trigger and Actions API overhaul
   2. [ ] theme() now takes only two arguments
   3. [ ] hook_theme() requires "variables" or "render element" instead of "arguments" to better integrate with drupal_render()
   4. [ ] drupal_alter() now takes at most 3 parameters by reference
   5. [ ] The $ret parameter has been removed from all Schema operations
   6. [ ] Update hooks now return strings or throw exceptions, and update_sql() is no more
   7. [ ] The signature of the callback from drupal_get_form() changed to add $form
   8. [ ] Replaced taxonomy_term_path(), hook_term_path(), language_url_rewrite(), and custom_url_alter_outbound() with hook_url_outbound_alter()
   9. [ ] Replaced custom_url_rewrite_inbound() with hook_url_inbound_alter()
  10. [ ] hook_load() signature and return value change
  11. [ ] Renamed menu_path_is_external() to url_is_external()
  12. [ ] Comment.timestamp split into 'created' and 'changed'
  13. [ ] New entity_info_cache_clear() API function
  14. [ ] Permissions have titles (required) and descriptions (optional)
  15. [ ] Custom menu API
  16. [ ] drupal_set_header() and drupal_get_header() renamed to drupal_add_http_header() and drupal_get_http_header()
  17. [ ] New hook_hook_info() added
  18. [ ] Taxonomy synonyms have been removed
  19. [ ] drupal_goto() follows parameters of url()
  20. [ ] hook_user_form(), hook_user_register() are gone
  21. [ ] hook_user_validate() and hook_user_submit() are gone
  22. [ ] hook_user_after_update() replaced by hook_user_update(), amended by hook_user_presave() for common operations
  23. [ ] url() 'query' field must be array
  24. [ ] Query string functions renamed

* ALPHA1 (2010-Jan-15)

   1. [ ] New hooks: hook_admin_paths() and hook_admin_paths_alter()
   2. [ ] theme('placeholder') replaced by drupal_placeholder()
   3. [ ] The function menu_valid_path() has been renamed to drupal_valid_path(), and its inputs have changed
   4. [ ] Language neutral content now has an explicit language associated with it
   5. [ ] New API function: format_username() and new hook: hook_username_alter()
   6. [ ] Functions called very often that need a drupal_static() variable can use an optimized way of calling that function
   7. [ ] A theme hook name followed by a double underscore ('__') is a default 'pattern'
   8. [ ] Preprocess functions need to now specify "theme_hook_suggestion(s)" instead of "template_file(s)"
   9. [ ] Use #theme='links__MODULE' or #theme='links__MODULE_EXTRA_CONTEXT' when adding links to a render array
  10. [ ] Use #type='link' for adding a single link to a render array, particularly for tables that include operation links like 'edit', 'delete', etc.
  11. [ ] Added entity_prepare_view() and hook_entity_prepare_view()
  12. [ ] New pattern for cross-database, performant, case-insensitive comparisons
  13. [ ] Comment rendering overhaul
  14. [ ] taxonomy_form_all() removed
  15. [ ] Module .info files can have configure line
  16. [] Forms are no longer automatically rebuilt when $form_state['storage'] is set

* ALPHA2 (2010-Feb-21)

   1. [ ] New method for altering the theme used to display a page (global $custom_theme variable removed)
   2. [ ] New update dependency system, affecting the order in which module updates are run
   3. [ ] Block tables renamed
   4. [ ] Block deltas are now specified as strings
   5. [ ] taxonomy_term_view() and taxonomy-term.tpl.php for term display
   6. [ ] Changed Clean URLs and Search settings page path
   7. [ ] Function menu_tree_data() now expects an array of links instead of a query results
   8. [ ] hook_update_index() only runs when searching enabled for a given module
   9. [ ] Format date types "small" and "large" have been changed to "short" and "long"
  10. [ ] "Boxes" have been renamed to "custom blocks"
  11. [ ] Remove moderate column from node_schema()
  12. [ ] theme_pager() no longer takes limit parameter
  13. [ ] theme_username() parameters changed
  14. [ ] form_clean_id() has been renamed to drupal_html_id()
  15. [ ] New #type 'text_format' for text format-enabled form elements

* ALPHA 3 (2010-Mar-21)

   1. [ ] New language negotiation API introduced
   2. [ ] HTTP Status code setting with drupal_add_http_header() changed (on top of a previous API change)
   3. [ ] WATCHDOG_EMERG was renamed to WATCHDOG_EMERGENCY
   4. [ ] system_retrieve_file() API cleanup
   5. [ ] menu_default_node_menu replaced with per-content type settings
   6. [ ] COMMENT_NODE_* constants have new names, but same values
   7. [ ] Drupal.parseJson has been removed and replaced with jQuery.parseJSON.

* ALPHA 4 (2010-Apr-27)

   1. [ ] New 'restrict access' parameter in hook_permission() for labeling unsafe permissions
   2. [ ] Removal of FAPI $form['#redirect'] and $_REQUEST['destination']
   3. [ ] User-configured time zones now serve as the default time zone for PHP date/time functions
   4. [ ] db_is_active() has been removed
   5. [ ] Node body field now requires normal field API usage
   6. [ ] Rename file to file_managed
   7. [ ] New hook_module_implements_alter
   8. [ ] Database prefixes are now per-connection
   9. [ ] Form submit buttons consistently grouped in actions array
  10. [ ] New constants for user registration settings, and the default has been changed to "Visitors, but administrator approval is required"
  11. [ ] hook_form_alter and hook_form_FORM_ID_alter run together for each module
  12. [ ] Arguments to xmlrpc() have changed
  13. [ ] Translatable Fields
  14. [ ] Filter table updates

* BETA 1 (6 Oct 2010) - may include Alpha 5-7

   1. [ ] file_directory_path() has been removed
   2. [ ] hook_form_BASE_FORM_ID_alter() is invoked for shared form constructors
   3. [ ] 'comment_form' form ID changed to 'comment_node_TYPE_form'
   4. [ ] Text formats (input formats) must be defined
   5. [ ] Text format (input format) identifier is now a machine name
   6. [ ] Arbitrary user data is harder to stash in the user object
   7. [ ] Two new functions added: hook_page_build() and hook_page_alter()
   8. [ ] Javascript and CSS loading changes
   9. [ ] Node, filter and comment modules tables renamed to singular
  10. [ ] 'post comments without approval' permission name changed
  11. [ ] MENU_CALLBACK meaning has changed for breadcrumbs, and some other menu API changes

* BETA 2 (22 Oct 2010)

   1. [ ] The datetime field type has been removed in favour of database engine specific types
   2. [ ] l() function class attribute

7.0 full release (4 Jan 2011) - May include Beta 3 or RC1 or RC2

   1. [ ] New 'properties' element of block information

* UNKNOWN

These changes were introduced somewhere in the 7.x development cycle, but we're not sure exactly when, sorry!

   1. [ ] $element['#post'] is gone
   2. [ ] node_load() and other entity loading cache behavior has changed
   3. [ ] $form_state['clicked_button'] is deprecated, use $form_state['triggering_element'] instead
